spring.application.name=NewSessionProject
spring.datasource.url=jdbc:postgresql://localhost:5432/NewSessionProject
spring.datasource.username=postgres
spring.datasource.password=@Yhjuik13
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create

#springdoc.swagger-ui.path=/swagger-ui.html

#spring.mongodb.uri=mongodb://localhost:27017/chatdb

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ruslan.absalam@gmail.com
spring.mail.password=ztiltsnsltiaapdn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
