spring.application.name=NewSessionProject
spring.datasource.url=${SPRING_LOCAL_DATASOURCE_URL}
spring.datasource.username=${SPRING_LOCAL_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_LOCAL_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create

app.upload.dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#springdoc.swagger-ui.path=/swagger-ui.html

spring.data.mongodb.uri=${SPRING_LOCAL_DATA_MONGODB_URI}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ruslan.absalam@gmail.com
spring.mail.password=ztiltsnsltiaapdn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
